spring:
  application:
    name: ribbon-mine


server:
  port: 12001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
#ribbon:
#  eureka:
#    enabled: false